name: ss2pl_build

on:
  push:
    paths:
      - '.github/workflows/ss2pl_build.yml'
      - 'common/**'
      - 'ss2pl/**'
      - 'third_party/**'
  pull_request:
    paths:
      - '.github/workflows/ss2pl_build.yml'
      - 'common/**'
      - 'ss2pl/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: Begin
        name: Begin
        run: |
          echo "Begin ${GITHUB_WORKFLOW}/${GITHUB_JOB}"

      - id: Checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: Install_apt
        name: Install_apt
        run: |
          sudo apt update -y
          sudo apt-get install -y $(cat build_tools/ubuntu.deps)

      - id: Submodule_init_recursive
        name: Submodule_init_recursive
        run: |
          git submodule update --init --recursive

      - id: Build_third_party_masstree
        name: Build_third_party_masstree
        run: |
            ./build_tools/bootstrap.sh

      - id: Build_third_party_mimalloc
        name: Build_third_party_mimalloc
        run: |
            ./build_tools/bootstrap_mimalloc.sh

      - id: Build_third_party_googletest
        name: Build_third_party_googletest
        run: |
            ./build_tools/bootstrap_googletest.sh

      - id: Build_ss2pl
        name: Build_ss2pl
        run: |
          cd ss2pl
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j

      - id: Test_ss2pl
        name: Test_ss2pl
        run: |
          cd ss2pl/build
          ctest --verbose --timeout 20 -j 100